server:
  port: 8081

spring:
  application:
    name: ms-auth
  datasource:
    url: jdbc:postgresql://${POSTGRES_SERVER}:5432/saas_auth_db
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:tu_password_aqui}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: sandbox.smtp.mailtrap.io
    port: 2525
    username: b28af248350116
    password: 658901eb58aa3c
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/